# playbook_create.yml

- name: create ubuntu device
  hosts: localhost
  tasks:

  - packet_device:
      project_id: 89b497ee-5afc-420a-8fb5-56984898f4df
      hostnames: myserver1
      operating_system: ubuntu_16_04
      plan: baremetal_0
      facility: sjc1

  - packet_device:
      project_id: 89b497ee-5afc-420a-8fb5-56984898f4df
      hostnames: myserver2
      operating_system: ubuntu_16_04
      plan: baremetal_0
      facility: sjc1

